#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the gryphonmoon network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0xb4,0xd5,0xc7,0x33,0x45,0x26,0xf1,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0xb4,0xd5,0xc7,0x33,0x45,0x4e,0x01,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
