#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the gryphonmoon network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xb9,0x5c,0xb5,0xb5,0x2e,0x2c,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xb9,0x5c,0xb5,0xb5,0xa3,0x5c,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H